import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileExists, fileContains } from '../../fs-utils.js'
import type { Adapter, AdapterFile, ConfigEdit, Detection } from '../types.js'

const MARKER = '# -- specdrive: RID traceability --'

const SNIPPET = `${MARKER}
# Auto-generated by \`specdrive init\`. Copies @RID-* pytest markers into
# JUnit XML <property> elements so that \`specdrive verify\` can trace them.
import pytest

@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(items):
    for item in items:
        for marker in item.iter_markers():
            if marker.name.startswith("RID_") or marker.name.startswith("RID-"):
                rid = marker.name.replace("_", "-")
                item.user_properties.append(("rid", rid))
`

async function checkFileForPattern(
  path: string,
  pattern: RegExp | string,
  label: string
): Promise<string | null> {
  if (!(await fileExists(path))) return null
  const content = await readFile(path, 'utf-8')
  const matches = typeof pattern === 'string' ? content.includes(pattern) : pattern.test(content)
  return matches ? label : null
}

async function gatherEvidence(dir: string): Promise<string[]> {
  const evidence: string[] = []

  const pyprojectHit = await checkFileForPattern(
    join(dir, 'pyproject.toml'),
    /\[tool\.pytest|pytest\b/,
    'pyproject.toml references pytest'
  )
  if (pyprojectHit) evidence.push(pyprojectHit)

  if (await fileExists(join(dir, 'pytest.ini'))) {
    evidence.push('pytest.ini exists')
  }

  const setupCfgHit = await checkFileForPattern(
    join(dir, 'setup.cfg'),
    '[tool:pytest]',
    'setup.cfg has [tool:pytest] section'
  )
  if (setupCfgHit) evidence.push(setupCfgHit)

  if (await fileExists(join(dir, 'conftest.py'))) {
    evidence.push('conftest.py exists')
  }

  for (const reqFile of ['requirements.txt', 'requirements-dev.txt', 'requirements-test.txt']) {
    const hit = await checkFileForPattern(
      join(dir, reqFile),
      /^pytest\b/m,
      `${reqFile} includes pytest`
    )
    if (hit) evidence.push(hit)
  }

  return evidence
}

export const pytestAdapter: Adapter = {
  framework: 'pytest',

  async detect(dir: string): Promise<Detection | null> {
    const evidence = await gatherEvidence(dir)
    if (evidence.length === 0) return null

    const hasCertainEvidence = evidence.some(
      (e) => e.includes('pytest.ini') || e.includes('pyproject.toml') || e.includes('setup.cfg')
    )
    const confidence = hasCertainEvidence ? 'certain' : evidence.length >= 2 ? 'likely' : 'possible'

    return { framework: 'pytest', confidence, evidence }
  },

  async files(dir: string): Promise<AdapterFile[]> {
    const conftestPath = join(dir, 'conftest.py')
    const alreadyInstalled = await fileContains(conftestPath, MARKER)
    if (alreadyInstalled) return []

    const exists = await fileExists(conftestPath)

    if (!exists) {
      return [
        {
          path: 'conftest.py',
          content: SNIPPET,
          description: 'pytest conftest hook for RID traceability',
        },
      ]
    }

    // Append to existing conftest
    const existing = await readFile(conftestPath, 'utf-8')
    const separator = existing.endsWith('\n') ? '\n' : '\n\n'
    return [
      {
        path: 'conftest.py',
        content: existing + separator + SNIPPET,
        description: 'append RID traceability hook to existing conftest.py',
      },
    ]
  },

  async configEdits(): Promise<ConfigEdit[]> {
    // pytest auto-discovers conftest.py — no config edit needed
    return []
  },
}
