import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileExists, fileContains } from '../../fs-utils.js'
import type { Adapter, AdapterFile, ConfigEdit, Detection } from '../types.js'

const MARKER = '// -- specdrive: RID traceability --'

const SETUP_FILE = 'specdrive.setup.ts'

const SNIPPET = `${MARKER}
// Auto-generated by \`specdrive init\`. Emits @RID-* tags as test annotations
// so that \`specdrive verify\` can trace them in JUnit XML output.
import { afterEach } from 'vitest'
import type { TaskMeta } from 'vitest'

afterEach(({ task }) => {
  // Vitest stores custom annotations on task.meta
  const meta = task.meta as TaskMeta & { rids?: string[] }
  const name = task.name ?? ''

  // Extract RIDs from test name (e.g. "@RID-AUTH-001" or "(RID-AUTH-001)")
  const ridRe = /RID-[A-Z][A-Z0-9-]*-\\d{3}/g
  let match: RegExpExecArray | null
  while ((match = ridRe.exec(name)) !== null) {
    meta.rids = meta.rids ?? []
    if (!meta.rids.includes(match[0])) {
      meta.rids.push(match[0])
    }
  }
})
`

const CONFIG_CANDIDATES = [
  'vitest.config.ts',
  'vitest.config.js',
  'vitest.config.mts',
  'vitest.config.mjs',
  'vite.config.ts',
  'vite.config.js',
]

async function findConfig(dir: string): Promise<string | null> {
  for (const name of CONFIG_CANDIDATES) {
    if (await fileExists(join(dir, name))) return name
  }
  return null
}

function noConfigEdit(): ConfigEdit {
  return {
    path: 'vitest.config.ts',
    description: `Add setupFiles: ['${SETUP_FILE}'] to your Vitest config`,
    safe: false,
    apply: async () => {},
    manual: [
      `No vitest config file found. Create one or add to your existing config:`,
      ``,
      `  // vitest.config.ts`,
      `  import { defineConfig } from 'vitest/config'`,
      `  export default defineConfig({`,
      `    test: {`,
      `      setupFiles: ['${SETUP_FILE}'],`,
      `    },`,
      `  })`,
    ].join('\n'),
  }
}

function appendToSetupFiles(configName: string): ConfigEdit {
  return {
    path: configName,
    description: `Add '${SETUP_FILE}' to setupFiles array in ${configName}`,
    safe: true,
    apply: async (baseDir: string) => {
      const filePath = join(baseDir, configName)
      const current = await readFile(filePath, 'utf-8')
      const updated = current.replace(/setupFiles\s*:\s*\[([^\]]*)\]/, (_match, inner) => {
        const trimmed = inner.trim()
        const sep = trimmed ? ', ' : ''
        return `setupFiles: [${trimmed}${sep}'${SETUP_FILE}']`
      })
      await writeFile(filePath, updated)
    },
    manual: `Add '${SETUP_FILE}' to the setupFiles array in ${configName}`,
  }
}

function addSetupFilesToTestBlock(configName: string): ConfigEdit {
  return {
    path: configName,
    description: `Add setupFiles to test config in ${configName}`,
    safe: true,
    apply: async (baseDir: string) => {
      const filePath = join(baseDir, configName)
      const current = await readFile(filePath, 'utf-8')
      const updated = current.replace(
        /test\s*:\s*\{/,
        `test: {\n    setupFiles: ['${SETUP_FILE}'],`
      )
      await writeFile(filePath, updated)
    },
    manual: `Add \`setupFiles: ['${SETUP_FILE}']\` inside the \`test: { }\` block in ${configName}`,
  }
}

function manualSetupEdit(configName: string): ConfigEdit {
  return {
    path: configName,
    description: `Add setupFiles to ${configName}`,
    safe: false,
    apply: async () => {},
    manual: [
      `Add the following to your Vitest config's \`test\` section in ${configName}:`,
      ``,
      `  test: {`,
      `    setupFiles: ['${SETUP_FILE}'],`,
      `  }`,
    ].join('\n'),
  }
}

export const vitestAdapter: Adapter = {
  framework: 'vitest',

  async detect(dir: string): Promise<Detection | null> {
    const evidence: string[] = []

    // Check package.json for vitest dependency
    const pkgPath = join(dir, 'package.json')
    if (await fileExists(pkgPath)) {
      const content = await readFile(pkgPath, 'utf-8')
      if (content.includes('"vitest"')) {
        evidence.push('package.json includes vitest dependency')
      }
    }

    // Check for vitest config
    const configName = await findConfig(dir)
    if (configName) {
      const content = await readFile(join(dir, configName), 'utf-8')
      if (content.includes('vitest') || content.includes('defineConfig')) {
        evidence.push(`${configName} exists`)
      }
    }

    if (evidence.length === 0) return null

    const confidence =
      evidence.length >= 2
        ? 'certain'
        : evidence.some((e) => e.includes('vitest dependency'))
          ? 'likely'
          : 'possible'

    return { framework: 'vitest', confidence, evidence }
  },

  async files(dir: string): Promise<AdapterFile[]> {
    const setupPath = join(dir, SETUP_FILE)
    if (await fileContains(setupPath, MARKER)) return []

    return [
      {
        path: SETUP_FILE,
        content: SNIPPET,
        description: 'Vitest setup file for RID traceability',
      },
    ]
  },

  async configEdits(dir: string): Promise<ConfigEdit[]> {
    const configName = await findConfig(dir)
    if (!configName) return [noConfigEdit()]

    const content = await readFile(join(dir, configName), 'utf-8')
    if (content.includes(SETUP_FILE)) return []

    if (content.includes('setupFiles')) {
      const arrayMatch = content.match(/setupFiles\s*:\s*\[([^\]]*)\]/)
      if (arrayMatch) return [appendToSetupFiles(configName)]
    }

    if (content.match(/test\s*:\s*\{/)) return [addSetupFilesToTestBlock(configName)]

    return [manualSetupEdit(configName)]
  },
}
