import { readFile, writeFile } from 'node:fs/promises'
import { parse, stringify } from 'yaml'
import type { Lockfile } from './types.js'

const LOCKFILE_HEADER = '# This file is auto-generated by specdrive. Do not edit manually.\n'

function validateRaw(raw: unknown): Lockfile | null {
  if (!raw || typeof raw !== 'object') return null

  const obj = raw as Record<string, unknown>
  if (obj.version !== 1) {
    if (typeof obj.version === 'number' && obj.version > 1) {
      throw new Error(`Lockfile version ${obj.version} is not supported. Please upgrade specdrive.`)
    }
    return null
  }

  if (!Array.isArray(obj.specs)) return null
  return raw as Lockfile
}

/**
 * Read and parse a lockfile. Returns null if the file doesn't exist.
 */
export async function readLockfile(path: string): Promise<Lockfile | null> {
  let content: string
  try {
    content = await readFile(path, 'utf-8')
  } catch {
    return null
  }

  return validateRaw(parse(content))
}

/**
 * Write a lockfile with a header comment.
 */
export async function writeLockfile(path: string, lock: Lockfile): Promise<void> {
  const content = LOCKFILE_HEADER + stringify(lock, { lineWidth: 120 })
  await writeFile(path, content, 'utf-8')
}
