import { describe, it, expect } from 'vitest'
import { join } from 'node:path'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { readLockfile, writeLockfile } from '../../src/lockfile.js'
import type { Lockfile } from '../../src/types.js'

describe('readLockfile', () => {
  it('reads a valid lockfile', async () => {
    const fixturesDir = join(import.meta.dirname, '..', 'fixtures')
    const lock = await readLockfile(join(fixturesDir, 'lock.yaml'))
    expect(lock).not.toBeNull()
    expect(lock!.version).toBe(1)
    expect(lock!.specs).toHaveLength(1)
    expect(lock!.specs[0].name).toBe('property-plugin-core')
    expect(lock!.specs[0].resolvedRef).toBe('local')
    expect(lock!.specs[0].ridCount).toBe(3)
  })

  it('returns null for missing file', async () => {
    const lock = await readLockfile('/nonexistent/lock.yaml')
    expect(lock).toBeNull()
  })

  it('returns null for invalid content', async () => {
    const dir = join(tmpdir(), `specdrive-lock-invalid-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'bad-lock.yaml')
    await writeFile(path, 'just a string', 'utf-8')
    const lock = await readLockfile(path)
    expect(lock).toBeNull()
  })

  it('throws for unsupported future version', async () => {
    const dir = join(tmpdir(), `specdrive-lock-version-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'v2-lock.yaml')
    await writeFile(path, 'version: 2\nspecs: []\n', 'utf-8')
    await expect(readLockfile(path)).rejects.toThrow('not supported')
  })

  it('returns null for non-numeric version', async () => {
    const dir = join(tmpdir(), `specdrive-lock-badver-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'badver-lock.yaml')
    await writeFile(path, 'version: "old"\nspecs: []\n', 'utf-8')
    const lock = await readLockfile(path)
    expect(lock).toBeNull()
  })

  it('returns null when specs is not an array', async () => {
    const dir = join(tmpdir(), `specdrive-lock-nospecs-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'nospecs-lock.yaml')
    await writeFile(path, 'version: 1\nspecs: not-an-array\n', 'utf-8')
    const lock = await readLockfile(path)
    expect(lock).toBeNull()
  })
})

describe('writeLockfile', () => {
  it('writes a lockfile with header comment', async () => {
    const dir = join(tmpdir(), `specdrive-lock-test-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'test-lock.yaml')

    const lock: Lockfile = {
      version: 1,
      specs: [
        {
          name: 'test-spec',
          source: 'path:../test',
          resolvedRef: 'local',
          installedAt: '2025-01-01T00:00:00.000Z',
          ridCount: 5,
        },
      ],
    }

    await writeLockfile(path, lock)
    const content = await readFile(path, 'utf-8')
    expect(content).toContain('# This file is auto-generated by specdrive')
    expect(content).toContain('test-spec')
    expect(content).toContain('version: 1')
  })

  it('round-trips through read/write', async () => {
    const dir = join(tmpdir(), `specdrive-lock-rt-${Date.now()}`)
    await mkdir(dir, { recursive: true })
    const path = join(dir, 'rt-lock.yaml')

    const lock: Lockfile = {
      version: 1,
      specs: [
        {
          name: 'my-spec',
          source: 'github:org/repo@v1.0',
          resolvedRef: 'abc123def',
          installedAt: '2025-06-15T12:00:00.000Z',
          ridCount: 10,
        },
      ],
    }

    await writeLockfile(path, lock)
    const read = await readLockfile(path)
    expect(read).toEqual(lock)
  })
})
